name: ⚡️ Deploy Documentation (Staging)
permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - staging
  # Trigger from CLI/SDK repo updates
  repository_dispatch:
    types: [docs-update-staging]

jobs:
  deploy-to-staging:
    uses: ./.github/workflows/af-deploy-common.yml
    with:
      environment: staging
      branch: staging
      network: ipfs
    secrets:
      af_api_key: ${{ secrets.AF_API_KEY }}
      gh_pat: ${{ secrets.GH_PAT }}
